[project]
name = "np-new-pagenation"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "bs4>=0.0.2",
    "certifi>=2025.1.31",
    "charset-normalizer>=3.4.1",
    "et-xmlfile>=2.0.0",
    "idna>=3.10",
    "loguru>=0.7.3",
    "lxml>=5.3.1",
    "openpyxl>=3.1.5",
    "pillow>=11.1.0",
    "pyqt5>=5.15.11",
    "pyqt5-qt5>=5.15.16",
    "pyqt5-sip>=12.17.0",
    "requests>=2.32.3",
    "soupsieve>=2.6",
    "tqdm>=4.67.1",
    "typing-extensions>=4.12.2",
    "urllib3>=2.3.0",
]
